// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('lengkapi profil klik cair', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('lengkapi profil klik cair', async function() {
    // Test name: lengkapi profil klik cair
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://borrower.klikcair.com/")
    // 2 | setWindowSize | 1366x712 | 
    await driver.manage().window().setRect({ width: 1366, height: 712 })
    // 3 | click | linkText=Lengkapi Profil | 
    await driver.findElement(By.linkText("Lengkapi Profil")).click()
    // 4 | click | name=nama_pic | 
    await driver.findElement(By.name("nama_pic")).click()
    // 5 | type | name=nama_pic | Henny Flora Panjaitan
    await driver.findElement(By.name("nama_pic")).sendKeys("Henny Flora Panjaitan")
    // 6 | click | css=.label-kc:nth-child(2) | 
    await driver.findElement(By.css(".label-kc:nth-child(2)")).click()
    // 7 | click | name=jabatan | 
    await driver.findElement(By.name("jabatan")).click()
    // 8 | click | name=jabatan | 
    await driver.findElement(By.name("jabatan")).click()
    // 9 | type | name=jabatan | -
    await driver.findElement(By.name("jabatan")).sendKeys("-")
    // 10 | click | name=ktp | 
    await driver.findElement(By.name("ktp")).click()
    // 11 | type | name=ktp | 1200
    await driver.findElement(By.name("ktp")).sendKeys("1200")
    // 12 | click | name=tempat_lahir | 
    await driver.findElement(By.name("tempat_lahir")).click()
    // 13 | type | name=tempat_lahir | Tarutung
    await driver.findElement(By.name("tempat_lahir")).sendKeys("Tarutung")
    // 14 | click | id=tgl_lahir | 
    await driver.findElement(By.id("tgl_lahir")).click()
    // 15 | click | css=.react-datepicker__day--030:nth-child(7) | 
    await driver.findElement(By.css(".react-datepicker__day--030:nth-child(7)")).click()
    // 16 | click | id=tgl_lahir | 
    await driver.findElement(By.id("tgl_lahir")).click()
    // 17 | type | id=tgl_lahir | 30-04-2001
    await driver.findElement(By.id("tgl_lahir")).sendKeys("30-04-2001")
    // 18 | click | css=.form-wrapper | 
    await driver.findElement(By.css(".form-wrapper")).click()
    // 19 | click | id=provinsi | 
    await driver.findElement(By.id("provinsi")).click()
    // 20 | select | id=provinsi | label=Sumatra Utara
    {
      const dropdown = await driver.findElement(By.id("provinsi"))
      await dropdown.findElement(By.xpath("//option[. = 'Sumatra Utara']")).click()
    }
    // 21 | click | id=kota | 
    await driver.findElement(By.id("kota")).click()
    // 22 | select | id=kota | label=Tapanuli Utara Kabupaten
    {
      const dropdown = await driver.findElement(By.id("kota"))
      await dropdown.findElement(By.xpath("//option[. = 'Tapanuli Utara Kabupaten']")).click()
    }
    // 23 | click | id=kecamatan | 
    await driver.findElement(By.id("kecamatan")).click()
    // 24 | select | id=kecamatan | label=Tarutung
    {
      const dropdown = await driver.findElement(By.id("kecamatan"))
      await dropdown.findElement(By.xpath("//option[. = 'Tarutung']")).click()
    }
    // 25 | click | id=kelurahan | 
    await driver.findElement(By.id("kelurahan")).click()
    // 26 | select | id=kelurahan | label=Hutatoruan I
    {
      const dropdown = await driver.findElement(By.id("kelurahan"))
      await dropdown.findElement(By.xpath("//option[. = 'Hutatoruan I']")).click()
    }
    // 27 | click | name=alamat | 
    await driver.findElement(By.name("alamat")).click()
    // 28 | type | name=alamat | Jalan Nahum Situmorang Sigompulon Tarutung no 77 Kabupaten Tapanuli Utara, Provinsi Sumatera Utara\n-
    await driver.findElement(By.name("alamat")).sendKeys("Jalan Nahum Situmorang Sigompulon Tarutung no 77 Kabupaten Tapanuli Utara, Provinsi Sumatera Utara\\n-")
    // 29 | type | name=alamat | Jalan Nahum Situmorang Sigompulon Tarutung no 77 Kabupaten Tapanuli Utara, Provinsi Sumatera Utara\n
    await driver.findElement(By.name("alamat")).sendKeys("Jalan Nahum Situmorang Sigompulon Tarutung no 77 Kabupaten Tapanuli Utara, Provinsi Sumatera Utara\\n")
    // 30 | click | css=.labelWithInput-Wrapper:nth-child(6) img | 
    await driver.findElement(By.css(".labelWithInput-Wrapper:nth-child(6) img")).click()
    // 31 | type | id=upload-selfie_file | C:\fakepath\IMG-20220130-WA0027.jpg
    await driver.findElement(By.id("upload-selfie_file")).sendKeys("C:\\fakepath\\IMG-20220130-WA0027.jpg")
    // 32 | click | css=.labelWithInput-Wrapper:nth-child(5) img | 
    await driver.findElement(By.css(".labelWithInput-Wrapper:nth-child(5) img")).click()
    // 33 | click | css=.labelWithInput-Wrapper:nth-child(4) .col-lg-10 | 
    await driver.findElement(By.css(".labelWithInput-Wrapper:nth-child(4) .col-lg-10")).click()
    // 34 | type | name=ktp | 1202017004010001
    await driver.findElement(By.name("ktp")).sendKeys("1202017004010001")
    // 35 | click | css=.labelWithInput-Wrapper:nth-child(5) img | 
    await driver.findElement(By.css(".labelWithInput-Wrapper:nth-child(5) img")).click()
    // 36 | type | id=upload-cid_file | C:\fakepath\WhatsApp Image 2022-04-29 at 14.13.20.jpeg
    await driver.findElement(By.id("upload-cid_file")).sendKeys("C:\\fakepath\\WhatsApp Image 2022-04-29 at 14.13.20.jpeg")
    // 37 | click | css=.big | 
    await driver.findElement(By.css(".big")).click()
    // 38 | click | name=alias_perusahaan | 
    await driver.findElement(By.name("alias_perusahaan")).click()
    // 39 | click | name=alias_perusahaan | 
    await driver.findElement(By.name("alias_perusahaan")).click()
    // 40 | click | name=alias_perusahaan | 
    await driver.findElement(By.name("alias_perusahaan")).click()
    // 41 | doubleClick | name=alias_perusahaan | 
    {
      const element = await driver.findElement(By.name("alias_perusahaan"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 42 | click | name=alamat | 
    await driver.findElement(By.name("alamat")).click()
    // 43 | type | name=alamat | Jalan Nahum Situmorang Sigompulon Tarutung no 77 Kabupaten Tapanuli Utara, Provinsi Sumatera Utara\n-
    await driver.findElement(By.name("alamat")).sendKeys("Jalan Nahum Situmorang Sigompulon Tarutung no 77 Kabupaten Tapanuli Utara, Provinsi Sumatera Utara\\n-")
    // 44 | click | name=kode_pos | 
    await driver.findElement(By.name("kode_pos")).click()
    // 45 | click | id=kelurahan | 
    await driver.findElement(By.id("kelurahan")).click()
    // 46 | click | id=provinsi | 
    await driver.findElement(By.id("provinsi")).click()
    // 47 | select | id=provinsi | label=Sumatra Utara
    {
      const dropdown = await driver.findElement(By.id("provinsi"))
      await dropdown.findElement(By.xpath("//option[. = 'Sumatra Utara']")).click()
    }
    // 48 | click | id=kota | 
    await driver.findElement(By.id("kota")).click()
    // 49 | select | id=kota | label=Tapanuli Utara Kabupaten
    {
      const dropdown = await driver.findElement(By.id("kota"))
      await dropdown.findElement(By.xpath("//option[. = 'Tapanuli Utara Kabupaten']")).click()
    }
    // 50 | click | id=kecamatan | 
    await driver.findElement(By.id("kecamatan")).click()
    // 51 | select | id=kecamatan | label=Tarutung
    {
      const dropdown = await driver.findElement(By.id("kecamatan"))
      await dropdown.findElement(By.xpath("//option[. = 'Tarutung']")).click()
    }
    // 52 | click | id=kelurahan | 
    await driver.findElement(By.id("kelurahan")).click()
    // 53 | select | id=kelurahan | label=Hutatoruan I
    {
      const dropdown = await driver.findElement(By.id("kelurahan"))
      await dropdown.findElement(By.xpath("//option[. = 'Hutatoruan I']")).click()
    }
    // 54 | click | name=deskripsi | 
    await driver.findElement(By.name("deskripsi")).click()
    // 55 | type | name=deskripsi | -
    await driver.findElement(By.name("deskripsi")).sendKeys("-")
    // 56 | click | name=sejak | 
    await driver.findElement(By.name("sejak")).click()
    // 57 | click | id=companyMonthlyIncome | 
    await driver.findElement(By.id("companyMonthlyIncome")).click()
    // 58 | select | id=companyMonthlyIncome | label=<3 Juta Rupiah
    {
      const dropdown = await driver.findElement(By.id("companyMonthlyIncome"))
      await dropdown.findElement(By.xpath("//option[. = '<3 Juta Rupiah']")).click()
    }
    // 59 | click | id=jumlah_karyawan | 
    await driver.findElement(By.id("jumlah_karyawan")).click()
    // 60 | select | id=jumlah_karyawan | label=< 50
    {
      const dropdown = await driver.findElement(By.id("jumlah_karyawan"))
      await dropdown.findElement(By.xpath("//option[. = '< 50']")).click()
    }
    // 61 | click | id=kategori_usaha | 
    await driver.findElement(By.id("kategori_usaha")).click()
    // 62 | select | id=kategori_usaha | label=Akuntan / Auditor
    {
      const dropdown = await driver.findElement(By.id("kategori_usaha"))
      await dropdown.findElement(By.xpath("//option[. = 'Akuntan / Auditor']")).click()
    }
    // 63 | click | name=nama_perusahaan | 
    await driver.findElement(By.name("nama_perusahaan")).click()
    // 64 | type | name=nama_perusahaan | -
    await driver.findElement(By.name("nama_perusahaan")).sendKeys("-")
    // 65 | click | id=tipe_perusahaan | 
    await driver.findElement(By.id("tipe_perusahaan")).click()
    // 66 | select | id=tipe_perusahaan | label=PT
    {
      const dropdown = await driver.findElement(By.id("tipe_perusahaan"))
      await dropdown.findElement(By.xpath("//option[. = 'PT']")).click()
    }
    // 67 | click | name=no_perusahaan | 
    await driver.findElement(By.name("no_perusahaan")).click()
    // 68 | type | name=no_perusahaan | 0
    await driver.findElement(By.name("no_perusahaan")).sendKeys("0")
    // 69 | click | name=email_perusahaan | 
    await driver.findElement(By.name("email_perusahaan")).click()
    // 70 | type | name=email_perusahaan | 0
    await driver.findElement(By.name("email_perusahaan")).sendKeys("0")
    // 71 | click | name=alias_perusahaan | 
    await driver.findElement(By.name("alias_perusahaan")).click()
    // 72 | type | name=alias_perusahaan | 0
    await driver.findElement(By.name("alias_perusahaan")).sendKeys("0")
    // 73 | click | css=.blue | 
    await driver.findElement(By.css(".blue")).click()
    // 74 | click | css=.spinner-border | 
    await driver.findElement(By.css(".spinner-border")).click()
  })
})
