// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('registrasi_negatif', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('registrasi_negatif', async function() {
    // Test name: registrasi_negatif
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("https://borrower.klikcair.com/login")
    // 2 | setWindowSize | 1366x712 | 
    await driver.manage().window().setRect({ width: 1366, height: 712 })
    // 3 | click | css=.mb-5 > .blue | 
    await driver.findElement(By.css(".mb-5 > .blue")).click()
    // 4 | click | css=.checkbox-inline | 
    await driver.findElement(By.css(".checkbox-inline")).click()
    // 5 | click | css=.big | 
    await driver.findElement(By.css(".big")).click()
    // 6 | click | name=noponsel | 
    await driver.findElement(By.name("noponsel")).click()
    // 7 | type | name=noponsel | 6277980
    await driver.findElement(By.name("noponsel")).sendKeys("6277980")
    // 8 | click | css=.block | 
    await driver.findElement(By.css(".block")).click()
    // 9 | mouseOver | css=.block | 
    {
      const element = await driver.findElement(By.css(".block"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | type | name=1 | 1
    await driver.findElement(By.name("1")).sendKeys("1")
    // 11 | type | name=2 | 1
    await driver.findElement(By.name("2")).sendKeys("1")
    // 12 | type | name=3 | 1
    await driver.findElement(By.name("3")).sendKeys("1")
    // 13 | type | name=4 | 1
    await driver.findElement(By.name("4")).sendKeys("1")
    // 14 | type | name=5 | 1
    await driver.findElement(By.name("5")).sendKeys("1")
    // 15 | type | name=6 | 1
    await driver.findElement(By.name("6")).sendKeys("1")
    // 16 | click | css=.block | 
    await driver.findElement(By.css(".block")).click()
  })
})
