// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Registrasi_positif Klik cair', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Registrasi_positif Klik cair', async function() {
    // Test name: Registrasi_positif Klik cair
    // Step # | name | target | value
    // 1 | open | /register | 
    await driver.get("https://borrower.klikcair.com/register")
    // 2 | setWindowSize | 1366x712 | 
    await driver.manage().window().setRect({ width: 1366, height: 712 })
    // 3 | click | name=setuju | 
    await driver.findElement(By.name("setuju")).click()
    // 4 | click | css=.big | 
    await driver.findElement(By.css(".big")).click()
    // 5 | click | name=noponsel | 
    await driver.findElement(By.name("noponsel")).click()
    // 6 | type | name=noponsel | 6282163975366
    await driver.findElement(By.name("noponsel")).sendKeys("6282163975366")
    // 7 | click | css=.block | 
    await driver.findElement(By.css(".block")).click()
    // 8 | type | name=1 | 9
    await driver.findElement(By.name("1")).sendKeys("9")
    // 9 | type | name=2 | 0
    await driver.findElement(By.name("2")).sendKeys("0")
    // 10 | type | name=3 | 2
    await driver.findElement(By.name("3")).sendKeys("2")
    // 11 | type | name=4 | 2
    await driver.findElement(By.name("4")).sendKeys("2")
    // 12 | type | name=5 | 7
    await driver.findElement(By.name("5")).sendKeys("7")
    // 13 | type | name=6 | 8
    await driver.findElement(By.name("6")).sendKeys("8")
    // 14 | click | css=.block | 
    await driver.findElement(By.css(".block")).click()
    // 15 | click | name=email_regist | 
    await driver.findElement(By.name("email_regist")).click()
    // 16 | type | name=email_regist | hennypanjaitan5@gmail.com
    await driver.findElement(By.name("email_regist")).sendKeys("hennypanjaitan5@gmail.com")
    // 17 | click | name=pass_regist | 
    await driver.findElement(By.name("pass_regist")).click()
    // 18 | type | name=pass_regist | Panjaitan5
    await driver.findElement(By.name("pass_regist")).sendKeys("Panjaitan5")
    // 19 | click | css=.form-group:nth-child(2) .iconViewPass | 
    await driver.findElement(By.css(".form-group:nth-child(2) .iconViewPass")).click()
    // 20 | click | name=repass | 
    await driver.findElement(By.name("repass")).click()
    // 21 | type | name=repass | Panjaitan5
    await driver.findElement(By.name("repass")).sendKeys("Panjaitan5")
    // 22 | click | css=.fa-eye | 
    await driver.findElement(By.css(".fa-eye")).click()
    // 23 | click | css=.mt-3 | 
    await driver.findElement(By.css(".mt-3")).click()
    // 24 | mouseOver | css=.mt-3 | 
    {
      const element = await driver.findElement(By.css(".mt-3"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 25 | mouseOut | css=.mt-3 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 26 | click | css=.big-rounded | 
    await driver.findElement(By.css(".big-rounded")).click()
    // 27 | type | name=email | hennypanjaitan5@gmail.com
    await driver.findElement(By.name("email")).sendKeys("hennypanjaitan5@gmail.com")
    // 28 | type | name=password | Panjaitan5
    await driver.findElement(By.name("password")).sendKeys("Panjaitan5")
  })
})
